uploads = []
generated = []

[[outputs]]
id = "JQRXpm7ZIVXYSOscoyJZU"
uri = "file://attached_assets/generated_audio/bg_music.mp3"
type = "audio"
title = "usdhkd-edge-bg-music"

[[outputs]]
id = "4i5c3nUSqt83Xw_HQtbtU"
uri = "file://attached_assets/generated_audio/voiceover.mp3"
type = "audio"
title = "usdhkd-edge-voiceover"

[[outputs]]
id = "dyFoJY-b5dXkDkVQRWOIO"
uri = "file://attached_assets/generated_audio/voiceover_2.mp3"
type = "audio"
title = "usdhkd-edge-voiceover"

[[outputs]]
id = "NHqoUG04iE8W2PErFTMI6"
uri = "file://attached_assets/generated_audio/voiceover_final.mp3"
type = "audio"
title = "usdhkd-edge-voiceover-final"
